// 代码生成时间: 2025-08-15 14:08:33
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.CreationHelper;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import play.mvc.Controller;
import play.mvc.Result;
import java.nio.file.Files;
import java.nio.file.Paths;

// ExcelFileGenerator is a controller class that generates an Excel file
public class ExcelFileGenerator extends Controller {
    
    // Generates an Excel file with sample data
    public Result generateExcelFile() {
        try {
            // Create a new Excel workbook
            Workbook workbook = new XSSFWorkbook();
            CreationHelper createHelper = workbook.getCreationHelper();
            
            // Create a new sheet
            String sheetName = "Sample Sheet";
            int sheetIndex = workbook.getNumberOfSheets();
            if (sheetIndex == 0) {
                sheetIndex++; // Reserve index 0 for default sheet
            }
            workbook.createSheet(sheetName).setSheetName(sheetName, sheetIndex);
            
            // Create a sample row and cell
            Row row = workbook.createSheet(sheetName).createRow(0);
            Cell cell = row.createCell(0);
            cell.setCellValue("Hello, this is an Excel file generated by Play Framework!");
            
            // Write the Excel file to the response output stream
            OutputStream out = response().asAttachment().out();
            workbook.write(out);
            out.close();
            workbook.close();
            
            // Return the file with a suggested filename
            return ok(out).as("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                         .withHeader("Content-Disposition", "attachment; filename=sample.xlsx");
        } catch (IOException e) {
            // Handle exceptions and return an error response
            return internalServerError("There was an error generating the Excel file.");
        }
    }
}